### ISSUE TITLE
http://idp.code4sa.org/ is down

### ISSUE THREAD

**Issue by adieyal** [OpenUpSA/odac-idp#2]

**Comment by petrus-jvrensburg** [comment]
I have it running at http://idp.demo4sa.org/, should I set up a DNS record
for http://idp.code4sa.org/ ?

**Comment by adieyal** [comment]
sorry - forgot that we weren't hosting it there. Yes - please add an entry.

Adi

On 28 March 2014 07:24, Petrus Janse van Rensburg
notifications@github.comwrote:

> I have it running at http://idp.demo4sa.org/, should I set up a DNS record
> for http://idp.code4sa.org/ ?
> 
> On 28 March 2014 04:58, Adi Eyal notifications@github.com wrote:
> 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/Code4SA/odac-idp/issues/2>
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/Code4SA/odac-idp/issues/2#issuecomment-38889800
> .

## 

Adi Eyal
Data Specialist
phone: +27 78 014 2469
skype: adieyalcas
linkedin: http://za.linkedin.com/pub/dir/Adi/Eyal
